import type { Flow } from '../types/flow.types';

export const exportFlowToJSON = (flow: Flow): void => {
  const flowData = JSON.stringify(flow, null, 2);
  const blob = new Blob([flowData], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  
  const link = document.createElement('a');
  link.href = url;
  link.download = `${flow.name.replace(/\s+/g, '_')}.json`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

export const importFlowFromJSON = (file: File): Promise<Flow> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    
    reader.onload = (event) => {
      try {
        const flowData = JSON.parse(event.target?.result as string);
        resolve(flowData);
      } catch (error) {
        reject(new Error('Invalid JSON file'));
      }
    };
    
    reader.onerror = () => {
      reject(new Error('Failed to read file'));
    };
    
    reader.readAsText(file);
  });
};

export const exportFlowToPython = (flow: Flow): void => {
  const pythonCode = generatePythonCode(flow);
  const blob = new Blob([pythonCode], { type: 'text/x-python' });
  const url = URL.createObjectURL(blob);
  
  const link = document.createElement('a');
  link.href = url;
  link.download = `${flow.name.replace(/\s+/g, '_')}.py`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

const generatePythonCode = (flow: Flow): string => {
  return `"""
${flow.description}
Generated by RPA Visual Playground
"""

from playwright.sync_api import sync_playwright

def run_automation():
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        page = browser.new_page()
        
        try:
${flow.steps.map(step => generateStepCode(step)).join('\n')}
        finally:
            browser.close()

def main():
    run_automation()

if __name__ == "__main__":
    main()
`;
};

const generateStepCode = (step: any): string => {
  const indent = '            ';
  
  switch (step.action) {
    case 'navigate':
      return `${indent}# Step ${step.stepId}: ${step.description || 'Navigate'}\n${indent}page.goto("${step.params.url}")`;
    
    case 'click':
      return `${indent}# Step ${step.stepId}: ${step.description || 'Click'}\n${indent}page.click("${step.params.selectors?.css || step.params.selectors?.xpath}")`;
    
    case 'input':
      return `${indent}# Step ${step.stepId}: ${step.description || 'Input'}\n${indent}page.fill("${step.params.selectors?.css}", "${step.params.value}")`;
    
    case 'wait':
      return `${indent}# Step ${step.stepId}: ${step.description || 'Wait'}\n${indent}page.wait_for_timeout(${step.params.timeout || 1000})`;
    
    default:
      return `${indent}# Step ${step.stepId}: ${step.action}`;
  }
};